Student/urls.py
from django.urls import path

from Student import views

app_name = 'Student'

urlpatterns = [
    path('', views.home, name='home'),
    path('show_data', views.show_data, name='show_data'),
    path('thingspeak_api', views.data_from_thingspeak, name='thingspeak_api'),
    path('fetch_datafrom_thingspeak', views.fetch_datafrom_thingspeak, name='fetch_datafrom_thingspeak'),
    path('live/', views.live_data, name='live_data'),
    path('graph_from_thingspeak', views.graph_from_thingspeak, name='graph_from_thingspeak'),
    path('query', views.query, name='query'),
    path('signup', views.handleSignUp, name="handleSignUp"),
    path('login', views.handeLogin, name="handleLogin"),
    path('logout', views.handelLogout, name="handleLogout"),

]

weather/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    # path('Student/',include('Student.urls',namespace='Student')),
    path('',include('Student.urls',namespace='Student')),
    path('admin/', admin.site.urls),
]

Student/views.py
from datetime import datetime
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
import requests
from django.contrib.auth  import authenticate,  login, logout
from django.contrib import messages 
from django.contrib.auth.models import User 


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


def home(request):
    return render(request,'authentication.html')

def show_data(request):
    return render(request,'index.html')



def data_from_thingspeak(request,template_name='data_from_thingspeak.html'):
    return render(request,template_name)

def fetch_datafrom_thingspeak(request):
    import urllib
    import json
    data = {}
    sensor_data = []
    if is_ajax(request):
        now = datetime.now()
        ok_date = (str(now.strftime('%Y-%m-%d %H:%M:%S')))
        custom_url = request.GET.get('id', None)
        try:
            with urllib.request.urlopen(custom_url) as url:
                s = url.read()
                data = json.loads(s)
            if data:
                sensor_data = {
                    'date': str(ok_date),
                    'temp': data['feeds'][1]['field1'],
                    'humidity': data['feeds'][1]['field2'],}
            else:
                sensor_data = {
                    'date': str(ok_date),
                    'temp': 'No Data',
                    'humidity': 'No Data',}
        except Exception as x:
            sensor_data = {
                'date': str(ok_date),
                'temp': 'Network Error',
                'humidity': 'Network Error',}
        

        data['result'] = sensor_data
    else:
        data['result'] = "Not Ajax"
        
    return JsonResponse(data)
    
def live_data(request):
    import requests
    response = requests.get('https://api.thingspeak.com/channels/1758870/feeds.json?api_key=5X7V8TFH88X86K86&results=2')
    data = response.json()
    city_weather={
            'temparature':data['feeds'][0]['field1'],
            'humidity':data['feeds'][0]['field2'],
    }

    return render(request,'live.html',{'city_weather':city_weather})      


def graph_from_thingspeak(request,template_name='graph_from_thingspeak.html'):
    return render(request,template_name)
  

def handleSignUp(request):
    if request.method=="POST":
        # Get the post parameters
        username=request.POST['username']
        email=request.POST['email']
        fname=request.POST['fname']
        lname=request.POST['lname']
        pass1=request.POST.get('pass1')
        pass2=request.POST['pass2']

        # check for errorneous input
        if not len(username)<10:
            messages.error(request, " Your user name must be under 10 characters")
            return redirect('Student:home')

        if not username.isalnum():
            messages.error(request, " User name should only contain letters and numbers")
            return redirect('Student:home')
        if (pass1!= pass2):
             messages.error(request, " Passwords do not match")
             return redirect('Student:home')
        # Create the user
        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name= fname
        myuser.last_name= lname
        myuser.save()
        return render(request,'index.html', {'messages':messages})

    else:
        return HttpResponse("404 - Not found")

def handeLogin(request):
    if request.method=="POST":
        # Get the post parameters
        loginusername=request.POST['loginusername']
        loginpassword=request.POST['loginpassword']

        user=authenticate(username= loginusername, password= loginpassword)
        if user is not None:
            login(request, user)
            return redirect("Student:show_data")
        else:
            messages.error(request, "Invalid credentials! Please try again")
            return redirect("Student:home")

    return HttpResponse("404- Not found")


def handelLogout(request):
    logout(request)
    messages.success(request, "Successfully logged out")
    return redirect('Student:home')

import pandas as pd

    
# Dataset Uses

def query(request,template_name='query.html'):
    
    def cal():
        if request.method == "POST":
            # Get the post parameters
            temp=request.POST['temp']
            temp = int(temp)
            
            url='https://drive.google.com/file/d/1bunQmOn82fcldEna9IG7wMejoLk1ue2T/view?usp=sharing'
            url='https://drive.google.com/uc?id=' + url.split('/')[-2]
            data = pd.read_csv(url)
            x=data[['created_at','field1']]
            p=x.loc[x.field1>temp]
            freq = p.to_html()
            return(freq)
    context={}
    context['calculated_value'] = cal()
    
    
    
    return render(request, template_name, context)

    

Student/templates/authentication.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Weather Monitoring</title>
    <style>
       {% load static %}
        body {
            background-image: url('{% static 'images/weather.jpg' %}');
            background-repeat:no-repeat;
            background-attachment:fixed;
            background-size:100% 100%;
        }
        h1{
            text-align: center;
            margin-top: 100px;
            color: rgb(241, 239, 239);
            font-size: 90px;
        }
        h2{
            text-align: center;
            margin-top: 110px;
            color: rgb(235, 226, 226);
            font-size: 160%;
            margin-right: 18%;
            margin-left: 18%;
            
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">WeatherMonitor</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                

            </ul>

            <!-- Button trigger login modal -->
            <button type="button" class="btn btn-success mr-2" data-toggle="modal" data-target="#loginModal">
                Login
            </button>

            <!-- Button trigger SignUp modal -->
            <button type="button" class="btn btn-success mr-2" data-toggle="modal" data-target="#signupModal">
                SignUp
            </button>
        </div>
    </nav>

    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>Message : </strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}

    <h1>Weather Monitoring System</h1>

<h2>
    Integrated Weather Monitoring system with multiple sensors like temperature, Wind Speed & Direction sensors
</h2>


    <!--  SignUp Modal -->
    <div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="signupModal"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="signupModaTitle">SignUp Here</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="/signup" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" name="username" id="username"
                                placeholder="Enter unique username" required>
                        </div>
                        <div class="form-group">
                            <label for="fname">First Name</label>
                            <input type="text" class="form-control" id="fname" name="fname"
                                placeholder="Enter first name" required>
                        </div>
                        <div class="form-group">
                            <label for="lname">Last Name</label>
                            <input type="text" class="form-control" id="lnane" name="lname"
                                placeholder="Enter last name" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" name="email" id="email" placeholder="Enter email"
                                required>
                        </div>
                        <div class="form-group">
                            <label for="pass1">Password</label>
                            <input type="password" class="form-control" name="pass1" id="pass1"
                                placeholder="Enter password" required>
                        </div>
                        <div class="form-group">
                            <label for="pass2">Confirm Password</label>
                            <input type="password" class="form-control" name="pass2" id="pass2"
                                placeholder="Enter confirm password" required>
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>

    <!--  Login Modal -->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModaTitle">Login Here</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="login" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" name="loginusername" id="loginusername"
                                placeholder="Enter unique username" required>
                        </div>
                        <div class="form-group">
                            <label for="pass">Password</label>
                            <input type="password" class="form-control" name="loginpassword" id="loginpassword"
                                placeholder="Enter password" required>
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

Student/templates/data_from_thingspeak.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  {% load static %}
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'font-awesome.css' %}" />
  <script src="{% static 'bootstrap.min.js' %}"></script>
<title>Weather Monitoring</title>

</head>

<body>
  <div class="container">
    <div class="row">
      <section class="col-md-12">
        <h2 class="page-header" style="text-align: center; color: white;">
          <b>Real-Time-data</b>
        </h2>
        <div class="row">
          <div class="form-group">
            <div class="row" style="margin-top: 15px">
              <div class="col-md-3">
                <label for="" class="" id="" >ENTER Thingspeak JSON URL:</label>
              </div>
              <div class="col-md-7">
                <input type="text" class="form-control" id="thingspeak_url" value="https://api.thingspeak.com/channels/1758870/feeds.json?api_key=5X7V8TFH88X86K86&results=2" />
              </div>
              <div class="col-md-2">
                <input id="open_url" class="btn btn-primary" value="Open URL" />
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <label for="" class="" id="" >Time Interval
                <small>(in seconds)</small>
                :</label>
            </div>
            <div class="col-md-4">
              <input type="text" class="form-control" name="" value="" id="id_interval"
                data-url="{% url 'Student:fetch_datafrom_thingspeak' %}" />
            </div>
          </div>
          <div class="row">
            <div class="text-center" style="margin-top: 10px">
              <button id="btn_show" class="btn btn-primary">SHOW</button>
            </div>
          </div>
          <div class="col-md-12" style="margin: top 15px">
            <div class="table-responsive">
              <table class="table table-bordered" id="sensor_content">
                <thead>
                  <tr>
                    <th>Date Time</th>
                    <th>Tempareture (degree)</th>
                    <th>Humidity (unit)</th>
                    <th>Delay</th>
                  </tr>
                </thead>
                <tbody id="sensor_content_body"></tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
    </section>
  </div>
  </div>
</body>

<script src="{% static  'jquery-3.3.1.min.js' %}"></script>
<script>
  $(document).ready(function () {
    $("#open_url").click(function () {
      uu = $("#thingspeak_url").val();
      window.open(uu);
    });

    let interval_time = 0;

    $("#btn_show").click(function () {
      interval_time = $("#id_interval").val() * 1000;
      let ajax_calling_url = $("#id_interval").data("url");
      let jsonurl = $("#thingspeak_url").val();
      $("#sensor_content_body").empty(); //empty the table on each click

      setInterval(function () {
        $.ajax({
          type: "get",
          url: ajax_calling_url,
          data: {
            id: jsonurl,
          },
          success: function (data1) {

                  function addZero(i) {
                    if (i < 10) {i = "0" + i}
                    return i;
                  }
                var date = new Date();
                var hours = addZero(date.getHours());
                var minutes = addZero(date.getMinutes());
                var seconds=addZero(date.getSeconds());

                var month = date.getMonth();
                var day = addZero(date.getDate());
                var year = date.getFullYear();

                var monthNames=[01,02,03,04,05,06,07,08,09,10,11,12];

                var p = hours+":"+minutes+":"+seconds;
                var q = year+"-"+addZero(monthNames[month])+"-"+day;

            $("#sensor_content_body").append(
              "<tr><td>" +
              data1.result.date +
              "</td><td>" +
              data1.result.temp +
              "</td><td>" +
              data1.result.humidity +
              "</td><td>" +
                 q+ " "+p +
                "</td></tr>"

            );
            return data1;
          },
          error: function () {
            console.log("Something Went Wrong!");
          },
        });
      }, interval_time); //time in milliseconds
    });
  });
</script>

</html>

Student/templates/graph_from_thingspeak.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  {% load static %}
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'font-awesome.css' %}" />
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <script src="{% static 'bootstrap.min.js' %}"></script>
  <title>Weather Monitoring</title>
  <style>
body{
            background-image: url('{% static 'images/graph1.jpg' %}');
            background-repeat: no-repeat;
            /* background-size: 100% 100%; */
}
#col{
  color: white;
}
  </style>
</head>

<body>
  <div class="container">
    <div class="row">
      <section class="col-md-12">
        <h2 class="page-header" style="text-align: center" id="col">
          <b>Real-Time-Graph</b>
        </h2>
        <div class="row">
          <div class="form-group">
            <div class="row" style="margin-top: 15px">
              <div class="col-md-3">
                <label for="" class="" id="col">ENTER Thingspeak JSON URL:</label>
              </div>
              <div class="col-md-7">
                <input type="text" class="form-control" id="thingspeak_url" value="https://api.thingspeak.com/channels/1758870/feeds.json?api_key=5X7V8TFH88X86K86&results=2" />
              </div>
              <div class="col-md-2">
                <button id="open_url" class="btn btn-primary" value="Open URL" >Open URL</button>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <label for="" class="" id="col">Time Interval
                <small>(in seconds)</small>
                :</label>
            </div>
            <div class="col-md-4">
              <input type="text" class="form-control" name="" value="" id="id_interval"
                data-url="{% url 'Student:fetch_datafrom_thingspeak' %}" />
            </div>
          </div>
          <div class="row">
            <div class="text-center" style="margin-top: 10px">
              <button id="btn_show" class="btn btn-primary">SHOW</button>
            </div>
          </div>
          <div class="col-md-12" style="margin: top 15px">
            <div class="col-md-12" style="margin-top: 15px">
                <div id="temp_graph_div"></div>
              </div>
          </div>
        </div>
    </div>
    </section>
  </div>
  </div>
</body>

<script src="{% static  'jquery-3.3.1.min.js' %}"></script>
<script>
  $(document).ready(function () {
    $("#open_url").click(function () {
      uu = $("#thingspeak_url").val();
      window.open(uu);
    });

    //let interval_time = 0;

    $("#btn_show").click(function () {
      let interval_time = $("#id_interval").val() * 1000;
      let ajax_calling_url = $("#id_interval").data("url");
      let jsonurl = $("#thingspeak_url").val();
      
      $("#sensor_content_body").empty(); //empty the table on each click
      fill_graph(jsonurl, ajax_calling_url, interval_time)
//time in milliseconds
    });
    function fill_graph(jsonurl, ajax_calling_url, interval_time) {
            function rand() {
              return Math.random();
            }

            var TEMP = {
              x: [],
              y: [],
              mode: "scatter",
              line: {
                color: "red",
                shape: "spline",
              },
              name: "Temp",
            };

            var datax = [TEMP];

            Plotly.newPlot("temp_graph_div", datax);

            var cnt = 0;

            var interval = setInterval(function () {
              var time = new Date();
              $.ajax({
                type: "get",
                url: ajax_calling_url,
                data: {
                  id: jsonurl,
                },
                success: function (data1) {
                  console.log(data1);
                  if (data1.hasOwnProperty("result")) {
                    let time = data1.result.date;
                    let wbt = data1.result.temp;
                    let update = {
                      x: [[time]],
                      y: [[wbt]],
                    };
                    Plotly.extendTraces("temp_graph_div", update, [0]);
                    if (++cnt === 100) clearInterval(interval);
                  }
                  return data1;
                },
                error: function () {
                  console.log("ERROR OCCURED");
                },
              });
            }, interval_time);
          } ; 
  });
</script>

</html>

Student/templates/index.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Weather Monitoring</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <style>
        {% load static %}
        body{
            background-image: url('{% static 'images/weatherr.jpg' %}');
            background-repeat: no-repeat;
            background-size: 100% 100%;
        }
    </style>
</head>

<body>
        <form  method="get" action="/logout">
            <button type="submit" class="btn btn-success">
                Logout
            </button>
        </form>
        <h1>Real Time Data from Cloud</h1>
    <div class="container">

        <a class="item btn btn-danger" href="{% url 'Student:thingspeak_api' %}"><h5 class="first">Data from ThingSpeak</h5></a>
        <a class="item btn btn-success" href="{% url 'Student:live_data' %}"><h5>Live Updated Data</h5></a>
        <a class="item btn btn-info" href="{% url  'Student:query' %}"><h5>Search Query</h5></a>
        <a class="item btn btn-warning" href="{% url  'Student:graph_from_thingspeak' %}"><h5>Graph View</h5></a>
        </div>
        
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

Student/templates/live.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Weather Monitoring</title>
    <style>
        h1 {text-align: center;}
    </style>
  </head>
<body>
<div id="main">
    <h1 text-align: center>Live Weather</h1>
    
    {% if city_weather %}

    <section class="vh-100" style="background-color: #4B515D;">
        <div class="container py-5 h-100">
      
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-8 col-lg-6 col-xl-4">
      
              <div class="card" style="color: #4B515D; border-radius: 35px;">
                <div class="card-body p-4">
      
                  
      
                  <div class="d-flex flex-column text-center mt-5 mb-4">
                    <h6 class="display-4 mb-0 font-weight-bold" style="color: #1C2331;"> {{city_weather.temparature}}°C </h6>
                  
                  </div>
      
                  <div class="d-flex align-items-center">
                    <div class="flex-grow-1" style="font-size: 1rem;">
                      <div><i class="fas fa-tint fa-fw" style="color: #868B94;"></i> <span class="ms-1"> <strong>Humidity: </strong>{{city_weather.humidity}} </span></div>
                    </div>
                  </div>
      
                </div>
              </div>
      
            </div>
          </div>
      
        </div>
      </section>
        
    {% endif %}
</div>
</body>
</html>

Student/templates/query.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Weather Monitoring</title>
    <style>
        #boxes {
          float: left;
          background: white;
          width: 45%;
          height:float;
          border-style: double;
          margin-top: -24%;
          margin-left: 28%;
        }
    
    
        #scroll {
          display: block;
          border: 0px solid red;
          padding: 5px;
          margin-top: 5px;
          width: 100%;
          height: 300px;
          overflow-y: scroll;
        }
        </style>
  </head>
  <body style="background-color:gray">
    <section id="cover" class="min-vh-100">
        <div id="cover-caption">
            <div class="container">
                <div class="row text-white">
                    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                        <h1 class="display-4 py-2 text-truncate" style="color:black"><strong>Search Query</strong></h1>
                            <hr>
                        <div class="px-2">
                            <form action="/query" method="post" class="justify-content-center" style="margin-top:2%">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="" style="color:black"><h4>Enter Temparature</h4></label>
                                    <input type="text" class="form-control"  name="temp" id="temp" required>
                                </div>
                                
                                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                                
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% if calculated_value %}

    <div id="boxes">
      <div id="scroll">
        {% if calculated_value %}
        <h3><strong>The Search value is :-</strong> {{calculated_value | safe}}</h3>
        {% endif %}
      </div>
    </div>
  
    {% endif %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>